[project]
name = "lgs-tool-bot"
version = "0.1.0"
description = "A OneBot protocol compatible chat bot"

requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0,<3",
    "websockets>=13.0,<14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
lgs-tool-bot = "lgs_tool_bot.__main__:main"
